[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake2 = "0.10.6"
common = { path = "../common" }
num-bigint = "0.4.6"
subtle = "2.6.1"
wasm-bindgen = "0.2.100"
wee_alloc = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
